WearOS version
Kaaveh/ComposeNews pull request #218
Opened 2024-07-14 11:15 UTC by rezazarchi

related to issue #176

2024-07-14 11:18 UTC, rezazarchi commented
Hey @Kaaveh 
I've added a new Android application module for Wear OS! I've included all the necessary dependencies and set up a basic MainActivity (it's empty for now).

I'd love to hear your thoughts on this initial setup. Please let me know if you have any feedback. Thanks!

2024-07-15 02:39 UTC, Kaaveh approved these changes, later dismissed

2024-07-15 02:40 UTC, Kaaveh commented
Hi @rezazarchi 
It's amazing! Please continue.

2024-08-03 07:16 UTC, rezazarchi commented
I changed modules structure to remove all WearOS-related dependencies from the current modules. We now have separated design, navigation, and UI modules for the WearOS version.

I added the remaining implementations for showing the list and details. However, there's still some work to do:

`QuadLineChart` still needs optimization for Wear UI. I couldn't resolve this issue yet.
We might improve the navigation to the details screen. I used `navController.navigate(***)` for this, but your previous solution for the details screen in the app module was slightly different.
The favorite feature hasn't been implemented yet.
Swipe functionality for each item hasn't been implemented yet.
The module structure might need review and refactoring if necessary.
Unit and UI tests haven't been implemented yet.

2024-08-03 12:53 UTC, Kaaveh submitted a review, later dismissed
Excellent!

2024-09-20 16:23 UTC, Kaaveh requested changes

2024-09-20 16:23 UTC, Kaaveh commented on app-watch/app/proguard-rules.pro
> +# Add project specific ProGuard rules here.
Can this file be deleted?

2024-09-20 16:23 UTC, Kaaveh commented on app-watch/navigation/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think this file can be deleted.

2024-09-20 16:23 UTC, Kaaveh commented on app-watch/ui/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think this file can be deleted.

2024-09-20 16:23 UTC, Kaaveh commented on gradle/libs.versions.toml
>  projectMinSdkVersion = "23"
I guess the build issue come from here! 🤔

2024-09-22 09:08 UTC, Kaaveh approved these changes, later dismissed

2024-09-22 17:22 UTC, Kaaveh approved these changes

2024-09-22 17:22 UTC, merged