Migrate Dependency Injection Framework from Hilt to Koin
Kaaveh/ComposeNews pull request #237
Opened 2024-11-26 14:15 UTC by cloner93

**Description:**

This Pull Request migrates the dependency injection framework used in the project from **Hilt** to **Koin**. The changes aim to simplify dependency management, improve modularity, and align with the team’s preferences or project goals.

**Changes Made:**

1. Replaced all Hilt annotations with Koin DSL methods (e.g., single, viewModel, module, etc.).
2. Updated Application class to initialize Koin with required modules:
3. Included feature-specific modules (e.g., marketListFeatureModule, marketDetailFeatureModule).
4. Included core modules (domainModule, repositoryModule, etc.).
5. Refactored ViewModel injection to use Koin's viewModel DSL.
6. Added new modules for api, data, domain, and feature layers.
7. Removed Hilt-related dependencies from the build.gradle files.

**Next Steps:**

- **Ensure team members are aligned with Koin usage**.
- **Document any guidelines or patterns for adding new modules and dependencies**.

2024-11-28 13:02 UTC, Kaaveh requested changes

2024-11-28 13:02 UTC, Kaaveh commented on app-watch/app/src/main/java/ir/composenews/ComposeNewsWearApplication.kt
> +                    marketListFeatureModule, marketDetailFeatureModule,
Break it into two lines.

2024-11-28 13:02 UTC, Kaaveh commented on app-watch/navigation/build.gradle.kts
> +        api(appWatch.ui)
Why do you make it `api` rather than `implementation`?

2024-11-28 13:02 UTC, Kaaveh commented on app-watch/ui/build.gradle.kts
> +        api(feature.marketlist)
And Why `api`?

2024-11-28 13:02 UTC, Kaaveh commented on app/proguard-rules.pro
>  -dontwarn dagger.internal.codegen.ComponentProcessor
Can we remove this line too?

2024-11-28 13:02 UTC, Kaaveh commented on app/src/main/java/ir/composenews/ComposeNewsApplication.kt
> +                    marketListFeatureModule, marketDetailFeatureModule,
Break this line into two lines

2024-11-28 13:02 UTC, Kaaveh commented on build-logic/convention/src/main/kotlin/KoinConventionPlugin.kt
> +    private fun Project.applyPlugins() {
I think this function can be removed.

2024-11-28 13:02 UTC, Kaaveh commented on build.gradle.kts
> -//        alias(ksp) apply false
Please put back this comment. We are currently working on an issue about `KSP`.

2024-11-28 13:02 UTC, Kaaveh commented on data/market-repository/build.gradle.kts
> +        api(data.marketRemote)
Why `api`?

2024-11-28 13:02 UTC, Kaaveh commented on feature/marketdetail/build.gradle.kts
> +        api(data.marketRepository)
Why `api`?

2024-11-28 13:02 UTC, Kaaveh commented on feature/marketdetail/src/main/java/ir/composenews/marketdetail/MarketDetailModule.kt
> +        )
Put it into one line.

2024-11-28 13:02 UTC, Kaaveh commented on feature/marketlist/build.gradle.kts
> +        api(data.marketRepository)
Why `api`?

2024-11-28 13:02 UTC, Kaaveh commented on feature/marketlist/src/main/java/ir/composenews/marketlist/marketListModule.kt
> +        )
Put it into one line

2024-11-28 13:02 UTC, Kaaveh commented on library/navigation/build.gradle.kts
> +        api(feature.marketdetail)
Why `api`?

2025-02-07 15:18 UTC, Kaaveh commented
Hey @cloner93 
Are you interested in finishing up this PR?

2025-02-22 14:14 UTC, cloner93 commented
Hello,
I sincerely apologize for the delay; I’ve been quite busy.

The main issue I encountered is that all modules need to be initialized within the `startKoin` scope to be accessible. There are a few possible solutions:

1. Using `api` instead of `implementation` – This allows access to all classes and values from the module. However, it makes the `app` module dependent on other modules. [(read more)](https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa)
2. Using `loadKoinModules(...) `– This method loads modules after `startKoin`. It seems like a good approach, but I haven't found an implementation that fully fits our project. [(read more)](https://insert-koin.io/docs/reference/koin-core/start-koin/#:~:text=of%20Koin%20Multiplatform.-,loading%20modules%20after%20startkoin,-You%20can't%20call)
3. A custom dependency injection approach, which I haven't explored yet.

These are my thoughts so far. If anyone has another solution, I'd appreciate your input.

2025-02-25 14:27 UTC, Kaaveh commented
Hi @cloner93 
I think the second approach is better. Considering these days, we are refactoring the presentation layer.

2025-08-19 17:15 UTC, closed without merging