Move SQLDelight to a Dedicated Module and Update Dependencies
Kaaveh/ComposeNews pull request #239
Opened 2024-12-02 04:34 UTC by VahidGarousi

This PR moves SQLDelight logic into a dedicated `ComposeNews.data.sqldelight` module, isolating `.sq` file to improve modularity and maintainability. 

### Key Changes:
- Created a new module for SQLDelight, making it the API for database interactions.
- Updated `build.gradle.kts` and `settings.gradle.kts` to reflect the new structure.
- Refactored `MarketDaoImpl.kt` to align with the new setup.

2024-12-06 12:15 UTC, Kaaveh requested changes

2024-12-06 12:15 UTC, Kaaveh commented on build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
> +//            apply("org.jetbrains.kotlin.kapt")
Can this comment be removed?

2024-12-06 12:15 UTC, Kaaveh commented on README.md
> +# ComposeNews new
Why did you add `new`?

2024-12-06 12:15 UTC, Kaaveh commented on data/sqldelight/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think this file can be deleted.

2024-12-07 02:59 UTC, VahidGarousi commented on data/sqldelight/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Removed

2024-12-07 02:59 UTC, VahidGarousi commented on README.md
> +# ComposeNews new
Fixed

2024-12-07 02:59 UTC, VahidGarousi commented on build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
> +//            apply("org.jetbrains.kotlin.kapt")
Removed

2024-12-07 05:28 UTC, Kaaveh approved these changes

2024-12-07 05:28 UTC, merged