Feature/handle view states
Kaaveh/ComposeNews pull request #49
Opened 2023-07-18 12:25 UTC by MohammadRezaei92

Handle Loading and Error view state in market list and detail page

2023-07-18 12:43 UTC, Kaaveh commented
Thanks Mohammad for you lovely PR! We review it as soon as possible! ❤️

2023-07-19 20:47 UTC, alibahaaa requested changes
Thanks @MohammadRezaei92 jan for contribution, While we can merge it now after solving failded test, it might be better to handle "improve data sync flow" task in a separate PR for better organization, anyway, great job on the PR!

2023-07-19 20:47 UTC, alibahaaa commented on domain/market/src/main/java/ir/kaaveh/domain/use_case/SyncMarketListUseCase.kt
> -    suspend operator fun invoke(): Boolean = repository.syncMarketList()
Tests failed, update NewsRepositoryImplTest class please. @MohammadRezaei92

2023-07-22 10:43 UTC, alibahaaa approved these changes
Well done @MohammadRezaei92 jan.

2023-07-22 10:43 UTC, merged